bin: add error checking to some scripts

diff --git a/bin/bin/configure_monitors b/bin/bin/configure_monitors
--- a/bin/bin/configure_monitors
+++ b/bin/bin/configure_monitors
@@ -5,6 +5,10 @@
 # NOTE: Assumes the external monitor is connected via DisplayPort and
 # named DP-1.
 
+_check() {
+	command -v "$1" > /dev/null
+}
+
 _external_is_connected () {
 	xrandr --query | grep -q 'DP-1 connected'
 }
@@ -24,6 +28,11 @@ _laptop () {
 _reconfigure_wallpaper () {
 	"$HOME"/.fehbg
 }
+
+if ! _check xrandr; then
+	echo "Error: xrandr not found"
+	exit 1
+fi
 
 if _external_is_connected; then
 	_external --primary
diff --git a/bin/bin/raise_or_run b/bin/bin/raise_or_run
--- a/bin/bin/raise_or_run
+++ b/bin/bin/raise_or_run
@@ -1,5 +1,9 @@
 #!/bin/sh
 
+_check() {
+	command -v "$1" > /dev/null
+}
+
 if [ $# -ne 2 ]; then
 	PROGNAME=$(basename "$0")
 	printf 'Usage %s <window_name> <command>\n' "$PROGNAME"
@@ -8,5 +12,10 @@ fi
 
 WINDOW_NAME=$1
 COMMAND=$2
+
+if ! _check wmctrl; then
+	echo "Error: wmctrl not found"
+	exit 1
+fi
 
 wmctrl -Fx -a "$WINDOW_NAME" || $COMMAND &
diff --git a/bin/bin/websearch b/bin/bin/websearch
--- a/bin/bin/websearch
+++ b/bin/bin/websearch
@@ -7,6 +7,10 @@ usage () {
 	exit 1
 }
 
+_check() {
+	command -v "$1" > /dev/null
+}
+
 if [ "$1" = '-p' ]; then
 	TERM=$(zenity --entry --text 'Search term:')
 	if [ $? != 0 ]; then
@@ -17,6 +21,13 @@ if [ "$1" = '-p' ]; then
 else
 	TERM=$(xclip -o)
 fi
+
+for program in zenity xclip xdg-open; do
+	if ! _check $program; then
+		printf 'Error: %s not found' "$program"
+		exit 1
+	fi
+done
 
 case $1 in
 	--google)
