Replace dunst with rofi

diff --git a/bin/bin/poweroptionsmenu b/bin/bin/poweroptionsmenu
--- a/bin/bin/poweroptionsmenu
+++ b/bin/bin/poweroptionsmenu
@@ -1,90 +1,58 @@
 #!/usr/bin/env bash
 
-	# This program is free software: you can redistribute it and/or modify
-	# it under the terms of the GNU General Public License as published by
-	# the Free Software Foundation, either version 3 of the License, or
-	# (at your option) any later version.
+# Rofi (or dmenu) interface for session actions
+# ======================================================================
 
-	# This program is distributed in the hope that it will be useful,
-	# but WITHOUT ANY WARRANTY; without even the implied warranty of
-	# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-	# GNU General Public License for more details.
-
-	# You should have received a copy of the GNU General Public License
-	# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-
-# Description
-#
-# A dmenu script to provide an interface for selecting session actions:
-# lock, logout, switch users, reboot, poweroff.
-#
-# This script is intended to be used in a BSPWM session.  As such, the
-# log out option uses a BSPWM-specific command.  Part of my dotfiles:
-# https://gitlab.com/protesilaos/dotfiles
-#
-# Debian Buster dependencies:
-# 	
-# 	apt install suckless-tools libnotify-bin
-#
-# Last full review on 2019-04-11
-
-# pass custom colours to dmenu command
-source "$HOME/.local/share/my_colours/active-theme.sh"
-
-# get the system-wide custom font
-source "$HOME/.local/share/my_custom_ui_font.sh"
-
-# Call this function with one argument for the prompt text
-my_dmenu() {
-	dmenu -i -p "$1" -nb "$background" -nf "$foreground" -sb "$color1" -sf "$background" -fn "$my_custom_ui_font"
+_pkill() {
+	if pgrep -x "$1"; then
+		pkill -x "$1"
+	fi
 }
 
-# Possible actions (see case statement at the end for the actual
-# commands)
-actions=('Lock screen' 'Quit session' Suspend Hibernate Reboot Shutdown)
-
-# List actions to choose from
-list_actions() {
-	# use printf to output array items on a new line
-	printf '%s\n' "${actions[@]}" | my_dmenu 'Power options'
+_kill_processes() {
+	_pkill bspwm_external_rules
+	_pkill sxhkd
+	_pkill melonpanel
+	_pkill feh
+	_pkill xcompmgr
 }
 
-choice="$(list_actions)"
+_checkdep() {
+	command -v "$1" >/dev/null || return 1
+}
 
-# Run the selected command
+_dynamic_menu() {
+	if _checkdep rofi; then
+		# use printf to output array items on a new line
+		rofi -dmenu -i -no-custom -p 'Power options'
+	elif _checkdep dmenu; then
+		dmenu -i -p 'Power options'
+	else
+		echo "Missing rofi or dmenu dependency." && exit 1
+	fi
+}
+
+# Possible actions
+actions=('Suspend'
+	'Log out'
+	'Reboot'
+	'Power off'
+	'Xmodmap and keyboard reload'
+	'Configure anew BSPWM monitors/desktops')
+
+# List actions to choose from.  Output array items on a new line.
+_list_actions() {
+	printf '%s\n' "${actions[@]}" | _dynamic_menu
+}
+
+choice="$(_list_actions)"
+
+# Run the selected command.
 case "$choice" in
-	L*)
-		slock
-		;;
-	Q*)
-		bspc quit
-		;;
-	Su*)
-		zzz
-		;;
-	H*)
-		ZZZ
-		;;
-	Sw*)
-		dm-tool switch-to-greeter
-		;;
-	R*)
-		doas reboot
-		;;
-	Sh*)
-		doas halt
-		;;
-	[a-zA-Z]*)
-		# This is for handling common typos
-		if [ -n "$(command -v notify-send 2> /dev/null)" ]; then
-			notify-send -i 'computer-fail' 'Session management' "ERROR: Option _${choice}_ does not exist"
-		else
-			echo "ERROR: Option _${choice}_ does not exist"
-		fi
-		exit 1
-		;;
-	*)
-		# Exit if dmenu receives no input
-		exit 1
-		;;
+	S*) zzz ;;
+	L*) _kill_processes && bspc quit ;;
+	R*) _kill_processes && doas reboot ;;
+	P*) _kill_processes && doas halt ;;
+	X*) _kbd_reset_and_xmodmap ;;
+	C*) bspwm_conf_reset_monitors ;;
 esac
diff --git a/bin/bin/tempusmenu b/bin/bin/tempusmenu
--- a/bin/bin/tempusmenu
+++ b/bin/bin/tempusmenu
@@ -1,56 +1,40 @@
 #!/usr/bin/env bash
 
-# tempusmenu --- dmenu interface for `tempus`.
-#
-# Provides an interactive menu from where to choose the argument that is
-# passed to the `tempus` script.  That will then live reload the session
-# to apply the new theme.  This functionality is integral to my dotfiles:
-# https://gitlab.com/protesilaos/dotfiles.
-#
-# Copyright (c) 2019 Protesilaos Stavrou <info@protesilaos.com>
-#
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, either version 3 of the License, or
-# (at your option) any later version.
-#
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-#
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+# tempusmenu --- dmenu-style interface for `tempus`.
+# ======================================================================
 
-# Check for dependency, else exit the given function that calls this.
-_depcheck() {
-	command -v "$1" >/dev/null || {
-		echo "Missing dependency: $1."
-		return 1
-	}
+if ! command -v rofi >/dev/null; then
+	echo "Missing rofi dependency."
+	return 1
+fi
+
+_check_dirs() {
+	if [ ! -d "$1" ]; then
+		echo "Missing path to Tempus theme directories."
+		exit 1
+	fi
 }
 
-_depcheck dmenu
-
-_filesource() {
-	if [ -f "$1" ]; then
-		source "$1"
+_check_files() {
+	if [ ! -f "$1" ]; then
+		echo "Missing path to Tempus theme files."
+		exit 1
 	fi
 }
 
 tempus_files="$HOME"/.local/share/my_colours
-[ -d "$tempus_files" ] || {
-	echo "Missing path to Tempus themes."
-	exit 1
-}
-
-tempus_active="$tempus_files"/active-theme.sh
 tempus_shell_files="$tempus_files"/shell/
+tempus_active="$tempus_files"/active-theme.sh
 
-dmenu_font="$HOME"/.local/share/my_custom_ui_font.sh
+_check_dirs "$tempus_files"
+_check_dirs "$tempus_shell_files"
+_check_files "$tempus_active"
 
-_filesource "$tempus_active"
-_filesource "$dmenu_font"
+# Get the unique identity of the active theme.  We want to inform the
+# user about it in the `rofi' prompt.
+tempus_active_name=$(sed '/tempus_/!d ; s,.*/,,' "$tempus_active")
+tempus_active_id="${tempus_active_name%.sh}"
+tempus_active_id="${tempus_active_id#tempus_}"
 
 _themes() {
 	# The parameter expansions here keep only the theme's unique name:
@@ -61,21 +45,11 @@ _themes() {
 	done < <(find "$tempus_shell_files" -type f -name '*.sh' -print0 | sort -z)
 }
 
-_dmenu() {
-	dmenu -p 'Select Tempus theme' -nb "${background:-'#000000'}" -nf "${foreground:-'#ffffff'}" \
-		-sb "${color5:-'#bb6688'}" -sf "${background:-'#000000'}" -fn "${my_custom_ui_font:-'DejaVu Sans-10'}"
+# Notice the two caret signs `^': to upcase the expanded variable.
+_rofi() {
+	rofi -dmenu -no-custom -p "Select Tempus theme (current is ${tempus_active_id^^})"
 }
 
-selection="$(_themes | _dmenu)"
+selection="$(_themes | _rofi)"
 
-if [ "$?" = 0 ]; then
-	case "$selection" in
-		autumn | classic | dawn | day | dusk | fugit | future | night | past | rift | spring | summer | tempest | totus | warp | winter)
-			tempus "$selection"
-			;;
-		*)
-			echo "Not a valid Tempus theme: $selection"
-			exit 1
-			;;
-	esac
-fi
+[ -n "$selection" ] && tempus "$selection"
