Don't edit tracked files when switching themes
This change adds a level of indirection: it introduces non-tracked files
that are updated when the active theme is changed.  These files are
then read by the various (tracked) config files to actually perform the
update.

diff --git a/bin/bin/ptp b/bin/bin/ptp
--- a/bin/bin/ptp
+++ b/bin/bin/ptp
@@ -1,22 +1,22 @@
 #!/usr/bin/env bash
 
-    # This program is free software: you can redistribute it and/or modify
-    # it under the terms of the GNU General Public License as published by
-    # the Free Software Foundation, either version 3 of the License, or
-    # (at your option) any later version.
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
 
-    # This program is distributed in the hope that it will be useful,
-    # but WITHOUT ANY WARRANTY; without even the implied warranty of
-    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-    # GNU General Public License for more details.
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
 
-    # You should have received a copy of the GNU General Public License
-    # along with this program.  If not, see <http://www.gnu.org/licenses/>.
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 # ptp (Print Tempus Palette) --- Prints the colour palette of the active
 # Tempus theme and colourises the value of each point accordingly.  Part
 # of my dotfiles: https://gitlab.com/protesilaos/dotfiles.
-# 
+#
 # The Tempus themes is a standalone project of mine, which is also
 # integrated into my custom desktop session.  For more about it, see:
 # https://protesilaos.com/tempus-themes.
@@ -30,20 +30,23 @@
 
 # This will work if the colours are in place (my dots rely on GNU Stow).
 my_colours="$HOME/.local/share/my_colours"
-active_theme="$my_colours/active-tempus-theme.sh"
-active_theme_content="$my_colours/active-theme-content"
+active_theme="$my_colours/active-theme.sh"
 
 # Check if the content of the active theme is present, else exit.
-[ -f "$active_theme" ] || { echo "ERROR: No available Tempus theme."; exit 1; }
+[ -f "$active_theme" ] || {
+	echo "ERROR: No available Tempus theme."
+	exit 1
+}
 
 # This cleans up the file that contains all the colour values.  It only
 # gets the hexadecimal RGB value (aka "HEX") of the 16-colour palette,
 # while omitting any other parameters.
-get_colours () {
-	sed '/color*/!d ; s,.*"\(#.*\)",\1,g' "$active_theme_content" | \
-	while IFS=$'\n' read -r line; do
-		echo -n "$line "
-	done
+get_colours() {
+	grep '^color' "$active_theme" |
+		while IFS=$'\n' read -r line; do
+			colour=$(echo "$line" | cut -d \" -f2)
+			echo -n "$colour "
+		done
 }
 
 # Declare an empty array, which we then populate with the HEX colour
@@ -51,11 +54,8 @@ get_colours () {
 # the colours.
 tempus_palette=()
 for i in $(get_colours); do
-	tempus_palette+=( "$i" )
+	tempus_palette+=("$i")
 done
-
-# Get the unique name of the active theme.
-tempus_slug="$(grep -o '[a-z]*\.sh' "$active_theme")"
 
 # The row with the colour values needs to not exceed the length of the
 # current terminal.  So we use conditional logic to print space-aware
@@ -68,17 +68,17 @@ colour_row() {
 	block='\u2588\u2588'
 
 	if [ "$columns" -gt 90 ]; then
-		echo -en "\\033[38;5;${i}m${block} ${tempus_palette[$i]} \\033[0m";
+		echo -en "\\033[38;5;${i}m${block} ${tempus_palette[$i]} \\033[0m"
 	elif [ "$columns" -gt 80 ]; then
-		echo -en "\\033[38;5;${i}m${block} ${tempus_palette[$i]:1} \\033[0m";
+		echo -en "\\033[38;5;${i}m${block} ${tempus_palette[$i]:1} \\033[0m"
 	else
-		echo -en "\\033[38;5;${i}m${tempus_palette[$i]} \\033[0m";
+		echo -en "\\033[38;5;${i}m${tempus_palette[$i]} \\033[0m"
 	fi
 }
 
-# Here we use parameter expansion to trim the final three characters.
-# No need to run an other command, such as sed or cut.
-echo "Tempus ${tempus_slug:0:-3}:"
+# Get the unique name of the active theme.
+theme_name=$(grep '^# theme: ' "$active_theme" | cut -d' ' -f4)
+echo "Tempus $theme_name"
 
 # Print the 16-colour palette in two rows that represent the standard
 # and bright variants.  Colourise each block with its respective colour
diff --git a/bin/bin/tempus b/bin/bin/tempus
--- a/bin/bin/tempus
+++ b/bin/bin/tempus
@@ -32,7 +32,6 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-
 # Error handling and help messages
 # --------------------------------
 _help_message() {
@@ -42,22 +41,25 @@ _help_message() {
 	# /path/to/tempus_classic.sh ==> classic
 	while IFS= read -r -d $'\0' line; do
 		line="${line##[a-z/_]*tempus_}"
-		printf "\\t%s\\n" "${line%.sh}"
+		printf '\t%s\n' "${line%.sh}"
 	done < <(find "$HOME"/.local/share/my_colours/shell/ -type f -name '*.sh' -print0 | sort -z)
 
 	echo "This assumes you have used STOW on my 'colours' directory (part of my dotfiles)"
 }
 
-[ "$#" -eq 1 ] || { _help_message; exit 1; }
+[ "$#" -eq 1 ] || {
+	_help_message
+	exit 1
+}
 
 tempus_theme="$1"
 
 # Is the theme light or dark?
 case "$tempus_theme" in
-	dawn|day|fugit|past|totus)
+	dawn | day | fugit | past | totus)
 		theme_variant=light
 		;;
-	autumn|classic|dusk|future|night|rift|spring|summer|tempest|warp|winter)
+	autumn | classic | dusk | future | night | rift | spring | summer | tempest | warp | winter)
 		theme_variant=dark
 		;;
 	*)
@@ -84,35 +86,50 @@ _sed_sync() {
 
 # Check for dependency, else exit the given function that calls this.
 _depcheck() {
-	command -v "$1" > /dev/null || { echo "Missing dependency: $1."; return 1; }
+	command -v "$1" >/dev/null || {
+		echo "Missing dependency: $1."
+		return 1
+	}
 }
 
-_wallpaper() {
-	# the wallpapers are defined manually at
-	# ~/pictures/theme/{light,dark}.jpg
-	wall_path="$HOME/pictures/theme"
-	wall_light="$wall_path/light.jpg"
-	wall_dark="$wall_path/dark.jpg"
+_x_and_shell() {
+	tempus_files="$HOME/.local/share/my_colours"
+	tempus_active_x="$tempus_files/active-theme.Xcolors"
+	tempus_active_sh="$tempus_files/active-theme.sh"
 
-	[ -d "$wall_path" ] || { echo "No path to: $wall_path"; return 1; }
-	[ -f "$wall_light" ] || { echo "No path to: $wall_light"; return 1; }
-	[ -f "$wall_dark" ] || { echo "No path to: $wall_dark"; return 1; }
-
-	_feh() {
-		feh --bg-fill "$1" &
+	_check_tempus() {
+		[ -n "$1" ] || {
+			echo "Path for Tempus themes is unavailable."
+			return 1
+		}
 	}
 
-	_depcheck feh
-	case "$theme_variant" in
-		l*) 
-			_feh "$wall_light"
-			;;
-		d*) 
-			_feh "$wall_dark"
-			;;
-	esac
+	ln -sf "${tempus_files}/shell/tempus_${tempus_theme}.sh" "$tempus_active_sh"
+	ln -sf "${tempus_files}/xcolors/tempus_${tempus_theme}.Xcolors" "$tempus_active_x"
+
+	own_script_update_running_terminals &
+
+	[ -f "$HOME/.Xresources" ] && xrdb -merge "$HOME/.Xresources"
 }
 
+_tmux() {
+	_depcheck tmux
+
+	. "$HOME/.local/share/my_colours/active-theme.sh"
+
+	cat <<-EOF >"$HOME/.tmux_colours.conf"
+		tempus_fg=$foreground
+		tempus_bg=$background
+		tempus_fg_alt=$foregroundalt
+		tempus_bg_alt=$backgroundalt
+		tempus_bg_dim=$backgrounddim
+	EOF
+
+	tmux source-file ~/.tmux_colours.conf
+	tmux source-file ~/.tmux.conf
+
+	tmux_update_vim &
+}
 
 # FIXME HELPME is it possible to change the Vim colorscheme from the
 # shell, so that all running Vim sessions inside the terminal switch to
@@ -127,63 +144,9 @@ _wallpaper() {
 _vim() {
 	_depcheck vim
 
-	_sed "s,\\(colorscheme \\).*,\\1tempus_${tempus_theme}," "$HOME"/.vim/vimrc
-}
-
-_x_and_shell() {
-	tempus_files="$HOME/.local/share/my_colours"
-	tempus_active_x="$tempus_files/active-tempus-theme.Xcolors"
-	tempus_active_sh="$tempus_files/active-tempus-theme.sh"
-	tempus_active_content="$tempus_files/active-theme-content"
-
-	_check_tempus() {
-		[ -n "$1" ] || { echo "Path for Tempus themes is unavailable."; return 1; }
-	}
-
-	_check_tempus "$tempus_files"
-	_check_tempus "$tempus_active_x"
-	_check_tempus "$tempus_active_sh"
-
-	# IMPORTANT once modified, let other processes use the new colours.
-	_sed_sync "s,\\(^source.*tempus_\\).*,\\1${tempus_theme}.sh," "$tempus_active_sh" && source "$tempus_active_sh"
-
-	# Update the X colours, so that new X programs inherit them.
-	_sed "s,\\(^#include.*tempus_\\).*,\\1${tempus_theme}.Xcolors\"," "$tempus_active_x"
-
-	# Create a new file as well that is used to get the colour values
-	# of the running terminal.
-	#
-	# This is used by: own_script_update_running_terminals
-	grep '^.*=' "$tempus_files/shell/tempus_${tempus_theme}.sh" > "$tempus_active_content"
-
-	# NOTE older scripts of mine, in need of review…  MATE Terminal is
-	# a fallback option, in case Xterm gives me problems (because MATE
-	# is my fallback desktop environment).
-	own_script_update_running_terminals &
-
-	_depcheck xterm
-
-	xresources="$HOME"/.Xresources
-	if [ -f "$xresources" ]; then
-		xrdb -merge "$xresources"
-	fi
-}
-
-_tmux() {
-	_depcheck tmux
-
-	_sed_sync "s/tempus_fg=\"#[a-zA-Z0-9]*\"/tempus_fg=\"${foreground}\"/ ; \
-	s/tempus_bg=\"#[a-zA-Z0-9]*\"/tempus_bg=\"${background}\"/ ; \
-	s/tempus_fg_alt=\"#[a-zA-Z0-9]*\"/tempus_fg_alt=\"${foregroundalt}\"/ ; \
-	s/tempus_bg_alt=\"#[a-zA-Z0-9]*\"/tempus_bg_alt=\"${backgroundalt}\"/ ; \
-	s/tempus_bg_dim=\"#[a-zA-Z0-9]*\"/tempus_bg_dim=\"${backgrounddim}\"/" "$HOME"/.tmux.conf
-
-	pgrep tmux > /dev/null || return 1
-
-	tmux source-file "$HOME/.tmux.conf"
-
-	# NOTE this is another script that is part of my dotfiles.
-	tmux_update_vim &
+	cat <<-EOF >"$HOME/.vim/current_scheme"
+		colorscheme tempus_$tempus_theme
+	EOF
 }
 
 _dunst() {
@@ -197,13 +160,13 @@ _dunst() {
 	# Change {back,fore}ground value for urgency_normal notifications
 	# Change {back,fore}ground value for urgency_critical notifications
 	gsed --follow-symlinks -i "s/\\(^separator_color.*\\)\\(#[0-9a-zA-Z]*\\)/\\1$backgrounddim/ ; \
-	s/\\(^frame_color.*\\)\\(#[0-9a-zA-Z]*\\)/\\1$backgroundalt/ ; \
-	/urgency_low/,/timeout/ s/\\(^b.*\\)\\(#[0-9a-zA-Z]*\\)/\\1$backgroundalt/ ; /urgency_low/,/timeout/ s/\\(^f.*\\)\\(#[0-9a-zA-Z]*\\)/\\1$foregroundalt/ ; \
-	/urgency_normal/,/timeout/ s/\\(^b.*\\)\\(#[0-9a-zA-Z]*\\)/\\1$background/ ; /urgency_normal/,/timeout/ s/\\(^f.*\\)\\(#[0-9a-zA-Z]*\\)/\\1$foreground/ ; \
-	/urgency_critical/,/timeout/ s/\\(^b.*\\)\\(#[0-9a-zA-Z]*\\)/\\1$color1/ ; /urgency_critical/,/timeout/ s/\\(^f.*\\)\\(#[0-9a-zA-Z]*\\)/\\1$background/" "$dunstrc"
+ s/\\(^frame_color.*\\)\\(#[0-9a-zA-Z]*\\)/\\1$backgroundalt/ ; \
+ /urgency_low/,/timeout/ s/\\(^b.*\\)\\(#[0-9a-zA-Z]*\\)/\\1$backgroundalt/ ; /urgency_low/,/timeout/ s/\\(^f.*\\)\\(#[0-9a-zA-Z]*\\)/\\1$foregroundalt/ ; \
+ /urgency_normal/,/timeout/ s/\\(^b.*\\)\\(#[0-9a-zA-Z]*\\)/\\1$background/ ; /urgency_normal/,/timeout/ s/\\(^f.*\\)\\(#[0-9a-zA-Z]*\\)/\\1$foreground/ ; \
+ /urgency_critical/,/timeout/ s/\\(^b.*\\)\\(#[0-9a-zA-Z]*\\)/\\1$color1/ ; /urgency_critical/,/timeout/ s/\\(^f.*\\)\\(#[0-9a-zA-Z]*\\)/\\1$background/" "$dunstrc"
 
 	# kill and reload dunst
-	if pgrep -x "dunst" > /dev/null; then
+	if pgrep -x "dunst" >/dev/null; then
 		pkill dunst && eval "$(dbus-launch)" &
 	fi
 }
@@ -215,13 +178,12 @@ _melonpanel() {
 	_depcheck melonpanel
 
 	# if pgrep -x melonpanel > /dev/null; then
-	# 	pkill -x melonpanel && melonpanel &
+	#  pkill -x melonpanel && melonpanel &
 	# fi
-	if pgrep -f melonpanel > /dev/null; then
+	if pgrep -f melonpanel >/dev/null; then
 		pkill -f melonpanel && melonpanel &
 	fi
 }
-
 
 _bspwm() {
 	# [ "$DESKTOP_SESSION" = 'bspwm' ] || return 1
@@ -242,22 +204,60 @@ _bspwm() {
 		_bc focused_border_color "$color6"
 	fi
 
-	bspwmrc="$HOME/.config/bspwm/bspwmrc"
+	bspwm_colours="$HOME/.config/bspwm/bspwm_colours"
 
-	[ -x "$bspwmrc" ] || { echo "Missing bspwmrc."; return 1; }
+	[ -f "$bspwm_colours" ] || {
+		echo "Missing bspwm_colours"
+		return 1
+	}
 
 	case "$theme_variant" in
-		l*)	
+		l*)
 			_sed "/^[^#].*active_border_color/ s,#[a-zA-Z0-9]*,$color1, ; \
-			/^[^#].*focused_border_color/ s,#[a-zA-Z0-9]*,$color4, ; \
-			/^[^#].*normal_border_color/ s,#[a-zA-Z0-9]*,$backgroundalt, ; \
-			/^[^#].*presel_feedback_color/ s,#[a-zA-Z0-9]*,$backgrounddim," "$bspwmrc"
+   /^[^#].*focused_border_color/ s,#[a-zA-Z0-9]*,$color4, ; \
+   /^[^#].*normal_border_color/ s,#[a-zA-Z0-9]*,$backgroundalt, ; \
+   /^[^#].*presel_feedback_color/ s,#[a-zA-Z0-9]*,$backgrounddim," "$bspwm_colours"
 			;;
 		d*)
 			_sed "/^[^#].*active_border_color/ s,#[a-zA-Z0-9]*,$color3, ; \
-			/^[^#].*focused_border_color/ s,#[a-zA-Z0-9]*,$color6, ; \
-			/^[^#].*normal_border_color/ s,#[a-zA-Z0-9]*,$backgroundalt, ; \
-			/^[^#].*presel_feedback_color/ s,#[a-zA-Z0-9]*,$backgrounddim," "$bspwmrc"
+   /^[^#].*focused_border_color/ s,#[a-zA-Z0-9]*,$color6, ; \
+   /^[^#].*normal_border_color/ s,#[a-zA-Z0-9]*,$backgroundalt, ; \
+   /^[^#].*presel_feedback_color/ s,#[a-zA-Z0-9]*,$backgrounddim," "$bspwm_colours"
+			;;
+	esac
+}
+
+_wallpaper() {
+	# the wallpapers are defined manually at
+	# ~/pictures/theme/{light,dark}.jpg
+	wall_path="$HOME/pictures/theme"
+	wall_light="$wall_path/light.jpg"
+	wall_dark="$wall_path/dark.jpg"
+
+	[ -d "$wall_path" ] || {
+		echo "No path to: $wall_path"
+		return 1
+	}
+	[ -f "$wall_light" ] || {
+		echo "No path to: $wall_light"
+		return 1
+	}
+	[ -f "$wall_dark" ] || {
+		echo "No path to: $wall_dark"
+		return 1
+	}
+
+	_feh() {
+		feh --bg-fill "$1" &
+	}
+
+	_depcheck feh
+	case "$theme_variant" in
+		l*)
+			_feh "$wall_light"
+			;;
+		d*)
+			_feh "$wall_dark"
 			;;
 	esac
 }
diff --git a/bin/bin/tempusmenu b/bin/bin/tempusmenu
--- a/bin/bin/tempusmenu
+++ b/bin/bin/tempusmenu
@@ -22,10 +22,12 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-
 # Check for dependency, else exit the given function that calls this.
 _depcheck() {
-	command -v "$1" > /dev/null || { echo "Missing dependency: $1."; return 1; }
+	command -v "$1" >/dev/null || {
+		echo "Missing dependency: $1."
+		return 1
+	}
 }
 
 _depcheck dmenu
@@ -37,9 +39,12 @@ _filesource() {
 }
 
 tempus_files="$HOME"/.local/share/my_colours
-[ -d "$tempus_files" ] || { echo "Missing path to Tempus themes."; exit 1; }
+[ -d "$tempus_files" ] || {
+	echo "Missing path to Tempus themes."
+	exit 1
+}
 
-tempus_active="$tempus_files"/active-tempus-theme.sh
+tempus_active="$tempus_files"/active-theme.sh
 tempus_shell_files="$tempus_files"/shell/
 
 dmenu_font="$HOME"/.local/share/my_custom_ui_font.sh
@@ -52,20 +57,20 @@ _themes() {
 	# /path/to/tempus_classic.sh ==> classic
 	while IFS= read -r -d $'\0' line; do
 		line="${line##[a-z/_]*tempus_}"
-		printf "%s\\n" "${line%.sh}"
+		printf '%s\n' "${line%.sh}"
 	done < <(find "$tempus_shell_files" -type f -name '*.sh' -print0 | sort -z)
 }
 
 _dmenu() {
 	dmenu -p 'Select Tempus theme' -nb "${background:-'#000000'}" -nf "${foreground:-'#ffffff'}" \
-	-sb "${color5:-'#bb6688'}" -sf "${background:-'#000000'}" -fn "${my_custom_ui_font:-'DejaVu Sans-10'}"
+		-sb "${color5:-'#bb6688'}" -sf "${background:-'#000000'}" -fn "${my_custom_ui_font:-'DejaVu Sans-10'}"
 }
 
 selection="$(_themes | _dmenu)"
 
 if [ "$?" = 0 ]; then
 	case "$selection" in
-		autumn|classic|dawn|day|dusk|fugit|future|night|past|rift|spring|summer|tempest|totus|warp|winter)
+		autumn | classic | dawn | day | dusk | fugit | future | night | past | rift | spring | summer | tempest | totus | warp | winter)
 			tempus "$selection"
 			;;
 		*)
