Improve restic’s repository verification
Also add bspwm rule to display backup script output.

diff --git a/restic/bin/do_backup b/restic/bin/do_backup
--- a/restic/bin/do_backup
+++ b/restic/bin/do_backup
@@ -2,18 +2,12 @@
 #
 # Run a backup of my home directory.
 
-_wlan_connect () {
-	if ! nmcli connection up Phunculist; then
-		echo 'Unable to connect. Exiting.'
-		exit 1
-	fi
-}
-
 _prepare () {
 	. "$HOME"/.profile.d/restic.sh
 }
 
 _do_backup () {
+	echo '* Performing backup'
 	exclude=$HOME/.config/restic/restic-exclude.txt
 	if ! restic --exclude-file="$exclude" backup "$HOME"; then
 		echo 'Unable to perform backup. Exiting.'
@@ -21,34 +15,35 @@ _do_backup () {
 	fi
 }
 
-_remove_old_snapshots () {
-	# Keep the most recent 7 daily snapshots, then 4 (remember, 7
-	# dailies already include a week!)  last-day-of-the-weeks and 11 or
-	# 12 last-day-of-the-months (11 or 12 depends if the 5 weeklies
-	# cross a month). And finally 100 last-day-of-the-year snapshots. All
-	# other snapshots are removed.
-	restic forget \
-	       --keep-daily 7 \
-	       --keep-weekly 5 \
-	       --keep-monthly 12 \
-	       --keep-yearly 100 \
-	       --prune
-}
-
 _verify () {
-	if ! restic check; then
-		echo 'Unable to verify repository.'
+	echo '* Verifying the repository'
+	# Verify the structure and consistency of the repository.  The
+	# option `--read-data-subset=n%’ also checks n%, randomly chosen,
+	# of the actual pack files.
+	if ! restic check --read-data-subset=1%; then
+		echo 'Cannot verify repository.'
+		exit 1
 	fi
 }
 
-echo '---------------Starting backup---------------'
-echo '* Connecting to wlan'
-_wlan_connect
-_prepare
-echo '* Performing backup'
-_do_backup
-echo '* Removing old snapshots'
-_remove_old_snapshots
-echo '* Verifying the repository'
-_verify
-echo '---------------Backup finished----------------'
+_remove_old_snapshots () {
+	echo '* Removing old snapshots'
+	# Keep the most recent 7 daily snapshots, then 4 (remember, 7
+	# dailies already include a week!) last-day-of-the-weeks and 11 or
+	# 12 last-day-of-the-months (11 or 12 depends if the 5 weeklies
+	# cross a month). And finally 100 last-day-of-the-year
+	# snapshots. All other snapshots are removed.
+	if ! restic forget \
+	     --keep-daily 7 \
+	     --keep-weekly 5 \
+	     --keep-monthly 12 \
+	     --keep-yearly 100 \
+	     --prune; then
+		echo 'Unable to remove old snapshots.'
+		exit 1
+	fi
+}
+
+echo '⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻Backup started⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻'
+_prepare && _do_backup && _verify && _remove_old_snapshots
+echo '⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻Backup finished⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻⸻'
