restic: ensure correct network is used

diff --git a/restic/bin/do_backup b/restic/bin/do_backup
--- a/restic/bin/do_backup
+++ b/restic/bin/do_backup
@@ -4,6 +4,13 @@
 
 . "$HOME/.profile.d/restic.sh"
 
+echo "Connecting to network Phunculist"
+if ! nmcli connection up Phunculist; then
+    echo "Unable to connect." >&2
+    exit 1
+fi
+echo
+echo "Running restic"
 restic --password-command="pass restic" \
        --exclude-file="$HOME/.config/restic/restic-exclude.txt" \
        --verbose \
