Use tabs for indentation in shell scripts

diff --git a/restic/bin/do_backup b/restic/bin/do_backup
--- a/restic/bin/do_backup
+++ b/restic/bin/do_backup
@@ -6,8 +6,8 @@
 
 echo "Connecting to network Phunculist"
 if ! nmcli connection up Phunculist; then
-    echo "Unable to connect." >&2
-    exit 1
+	echo "Unable to connect." >&2
+	exit 1
 fi
 echo
 echo "Running restic"
