restic: run do_backup from systemd

diff --git a/restic/bin/do_backup b/restic/bin/do_backup
--- a/restic/bin/do_backup
+++ b/restic/bin/do_backup
@@ -6,28 +6,19 @@ set -o errexit                  # abort on nonzero exitstatus
 set -o nounset                  # abort on unbound variable
 set -o pipefail                 # don't hide errors within pipes
 
-printf '────── Backup started: %s ───────\n' "$(date '+%a %H:%M')"
-
-echo '⮕ Connecting to network Phunculist'
-. "$HOME"/.rc.d/wifi.sh
-if ! wifi Phunculist; then
-	echo '❌ Unable to connect to network Phunculist. Exiting.'
+if ! iwctl station wlan0 connect Phunculist; then
+	echo 'Unable to connect to network Phunculist. Exiting.'
 	exit 1
 fi
 
-. "$HOME"/.profile.d/restic.sh
-
-echo '⮕ Performing backup'
 if ! restic backup "$HOME"                                    \
      --exclude-file="$HOME/.config/restic/restic-exclude.txt" \
-     --verbose=2                                              \
-		| tee /tmp/do_backup_log.txt; then
-	echo '❌ Unable to perform backup. Exiting.'
+     --no-scan                                                \
+     --quiet ; then
+	echo 'Unable to perform backup. Exiting.'
 	exit 1
 fi
-echo
 
-echo '⮕ Removing old snapshots'
 # Keep the most recent 7 daily snapshots, then 4 (remember, 7 dailies already
 # include a week!) last-day-of-the-weeks and 11 or 12 last-day-of-the-months (11
 # or 12 depends if the 5 weeklies cross a month). And finally 100
@@ -37,11 +28,9 @@ if ! restic forget      \
      --keep-weekly 5    \
      --keep-monthly 12  \
      --keep-yearly 100  \
+     --cleanup-cache    \
      --prune            \
-     --verbose=2        \
-		| tee --append /tmp/do_backup_log.txt ; then
-	echo '❌ Unable to remove old snapshots.'
+     --quiet ; then
+	echo 'Unable to remove old snapshots.'
 	exit 1
 fi
-
-printf '────── Backup finished: %s ──────\n' "$(date '+%a %H:%M')"
